services:
  client:
    build:
      context: ${CLIENT_PATH}
      args:
        REACT_APP_SERVER_URL: "http://localhost:3000"
    ports:
      - "80:80"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3000  # 서버의 URL을 환경 변수로 전달
    networks:
      - webnet
    depends_on:
      - server

  server:
    image: "ausitn/server:latest"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMO_TABLE_NAME=${DYNAMO_TABLE_NAME}
      - TERRAFORM_BUCKET=${TERRAFORM_BUCKET}
      - TERRAFORM_LAMBDA_FUNCTION=${TERRAFORM_LAMBDA_FUNCTION}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DOCKER_USERNAME=ausitn
    networks:
      - webnet

networks:
  webnet:
    driver: bridge


    # asdfasdfsdf