services:
  client:
    build:
      context: ${CLIENT_PATH}  # 환경 변수를 사용하여 경로 설정
    ports:
      - "80:80"
    volumes:
      - ${CLIENT_PATH}:/app  # 환경 변수를 사용하여 경로 설정
    depends_on:
      - server

  server:
    build:
      context: ${SERVER_PATH}
    ports:
      - "3000:3000"
    volumes:
      - ${SERVER_PATH}:/app
