services:
  client:
    build:
      context: ${CLIENT_PATH}  # 환경 변수를 사용하여 경로 설정
    ports:
      - "80:80"
    volumes:
      - ${CLIENT_PATH}:/app
    depends_on:
      - server

  server:
    build:
      context: ${SERVER_PATH}
    ports:
      - "3000:3000"
    volumes:
      - ${SERVER_PATH}:/app
    environment:
      - DATABASE_HOST=host.docker.internal  # 로컬 PostgreSQL에 연결
      - DATABASE_PORT=5432  # PostgreSQL의 기본 포트
      - DATABASE_USER=postgres  # PostgreSQL의 기본 사용자
      - DATABASE_PASSWORD=1234  # PostgreSQL 비밀번호
      - DATABASE_NAME=my_test  # PostgreSQL 데이터베이스 이름

