services:
  client:
    build:
      context: ${CLIENT_PATH}
      args:
        REACT_APP_SERVER_URL: "http://localhost:3000"
    ports:
      - "80:80"
    volumes:
      - ${CLIENT_PATH}:/app
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3000  # 서버의 URL을 환경 변수로 전달
    networks:
      - webnet

  server:
    build:
      context: ${SERVER_PATH}
    ports:
      - "3000:3000"
    volumes:
      - ${SERVER_PATH}:/app
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=my_test
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

# Test# Test