name: Deploy
on:
  push:
    branches: [ "deploy" ]

env:
  APP_VERSION: "${{ github.run_number }}"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub or another registry (assumes using Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push server image
      - name: Build and push server Docker image
        run: |
          docker build ./server -t ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION 
          docker push ${{ secrets.DOCKER_USERNAME }}/server:$APP_VERSION

          
      - name: List docker image
        run: docker image ls
      
      # Build and push client image
      - name: Build and push client Docker image
        run: |
          docker build ./client -t ${{ secrets.DOCKER_USERNAME }}/client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/client:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/kj-***
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export DYNAMO_TABLE_NAME=${{ secrets.DYNAMO_TABLE_NAME }}
            export TERRAFORM_BUCKET=${{ secrets.TERRAFORM_BUCKET }}
            export TERRAFORM_LAMBDA_FUNCTION=${{ secrets.TERRAFORM_LAMBDA_FUNCTION }}
            export ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/client:latest
            sudo docker-compose -f docker-compose.yml up -d
